const defaultWordGroups = [
  ['genuine','genuinely'],
  ['fertilizer','fertility'],
  ['fatally','fatality', 'fatal'],
  ['handle', 'cope', 'tackle', 'solve', 'resolve'],
  ['growl', 'roar'],
  ['bound', 'bounce', 'hop', 'leap'],
  ['spill', 'spit', 'split', 'spilt'],
  ['border', 'broaden'],
  ['sedate', 'seduce'],
  ['depend on', 'rely on', 'contingent on', 'rest on', 'be subject to'],
  ['fatality', 'facilitate'],
  ['vibrant', 'vitality', 'vibration'],
  ['slice', 'slash'],
  ['perfect - v', 'perfect - adj'],
  ['oceanic'],
  ['litigation', 'prosecution', 'sue'],
  ['injured'],
  ['council', 'consult'],
  ['mutual', 'mutualism'],
  ['laboratory'],
  ['burn', 'burned', 'burnt', 'burst'],
  ['religion', 'religiously', 'religious'],
  ['fungus', 'fungi'],
  ['tear - v', 'tear - n', 'torn', 'tore', 'torment', 'torture'],
  ['attribute to', 'be subject to'],
  ['analyses', 'analyse', 'analysis - 发音都不一样'],
  ['natural','nature'],
  ['economic','economy'],
  ['recipe', 'reception'],
  ['hinder', 'inhibit', 'deter'],
  ['coincide', 'coincidence'],
  ['opportunistic'],
  ['culture', 'cultivate', 'raise', 'rear', 'nurture'],
  ['literature', 'literacy', 'literal', 'literary','literate', 'illiterate'],
  ['facilitate', 'facility'],
  ['screen', 'filter'],
  ['rob', 'lob', 'lobby', 'loft', 'robe'],
  ['synthetic', 'synchronize', 'synchronic'],
  ['wire', 'weird', 'hard-wired'],
  ['attribute-verb'],
  ['unwind', 'rewind', 'wind'],
  ['coincide', 'coincidence'],
  ['den', 'dam'],
  ['penguin', 'pungent'],
  ['gravely', 'gravity'],
  ['scene', 'scenario', 'sequence', "episode"],
  ['loon', 'loom', 'lone'],
  ['rein', 'reign'],
  ['official', 'authority', 'administration'],//v,n  n
  ['icon', 'iconic', 'ironic'],
  ['fling', 'flying'],
  ['illicit', 'illegal'],
  ['bear', 'beard'],
  ['innovative', 'original'],
  ['intrigue', 'fascinate'],
  ['strategy', 'strategic'],
  ['prone', 'probe'],
  ['expanse', 'expansion', 'expand', 'expansive'],
  ['oversee', 'overlook'],
  ['fabric', 'fabricate', 'prefabricate'],
  ['saw', 'sew', 'sewer', 'sewer'],
  ["clan", "claw", 'clay'],
  ["hallow", "halloween", 'hollow'],
  ["contrary", "contrast"],
  ["reality", "realization", "real", "realistic", "realize", "realistically"],
  ["stalwart", "steward"],
  ["fairy", "fair"],
  ["iconic", "ironic"],
  ["gateway", "getaway"],
  ["venture", "adventure"],
  ["sore", "soar", "sour"],
  ["fierce", "fiery"],
  ["delve", "deplete"],
  ["paste", "pasta"],
  ["luxurious", "extravagance", "luxury"],
  ["immense", "imminent", "eminent"],
  ["heaven", "haven"],
  ["invoke", "revoke"],
  ["deference", "defer", "deter"],
  ["proactively", "provocatively"],
  ["bunk", "bunker"],
  ["ceremony", "cemetery"],
  ["crush", "crash", "rush"],
  ["hype", "hyper"],
  ["sympathy", "empathy"],
  ["reverent", "revere", "reverence", "reverend"],
  ["sublime", "subtle"],
  ["idyllic"],
  ["horde", "herd"],
  ["sheriff", "chef"],
  ["patron", "patrol", "patriot", "petrol", 'petroleum'],
  ["rural", "rustic"],
  ["lush", "verdant"],
  ["meticulously", "malicious", "mischievous"],
  ["as opposed to", "instead of"],
  ["feat", "feast"],
  ["abundant", "abandon", "abandoned"],
  ["scare", "scarce", "scarcity"],
  ["shelves", "shelter"],
  ["congested", "contingent", "consign", 'consent'],
  ["tap", "tap into"],
  ["strike", "stroke", "struck", "stoke", "stork"],
  ["considerable", "considerate"],
  ["initiative", "initiate", "initial"],
  ["panoramic", "promenade", "lemonade"],
  ["prey", "predator", "predate", "pray", "priest"],
  ["inhabit", "habitat", "habitation", "inhabitant"],
  ["epidemic", "endemic"],
  ["eternal", "ethereal"],
  ["turf", "tuft"],
  ["aboard", "abroad", "board"],
  ["cottage", "cabbage", "carriage"],
  ["equine", "aquatic"],
  ["boast", "boost"],
  ["scrub", "succumb", "scurry"],
  ["spirit", "sprite"],
  ["indulging", "undulating"],
  ["flip", "flap"],
  ["captivate", "captive", "capture", "cavity"],
  ["lag", "lug", "tug"],
  ["loyal", "royal"],
  ["participate", "precipitate", "anticipate"],
  ["unite", "unit"],
  ["potato", "tomato"],
  ["couch", "coach"],
  ["avenue", "venue", "convention", "convene", 'convenience', "conventional"],
  ["vibrant", "vibrance", "vibe"],
  ["flank", "plank"],
  ["pedal", "paddle"],
  ["dust", "dusk", "dawn"],
  ["adorn", "adore"],
  ["bow", "bowl"],
  ["spire", "spine", "spindly", "spin"],
  ["stew", "strew", "straw"],
  ["captain", "subtitle", "caption"],
  ["sector", "section"],
  ["torch", "torture"],
  ["wonder", "wander"],
  ["concentric", "concentrate"],
  ["stump", "stamp"],
  ["incline", "recline", "decline", "descend", "descendant", "descent"],
  ["rumble", "scramble", "ramble"],
  ["hammock", "hummock"],
  ["forage", "forge", "foliage"],
  ["swamp", "swath"],
  ["clamp", "clump"],
  ["crucial", "cruel"],
  ["hospitable", "hostile", "hostel"],
  ['bear', 'born', 'bore'],
  ["tempt", "attempt", "contemporary", "contempt", "temp", "confront", "conform", "obey", "comply"],
  ["lavender", "vanilla"],
  ["assume", "unassuming"],
  ["reed", "reef"],
  ["specialist", "specialize", "special", "specialty"],
  ["handful", "handy"],
  ["incentive", "sensitive", "sensitize"],
  ["rough", "rugged", "jagged"],
  ["leash", "lease"],
  ["beckon", "reckon", "reckoning"],
  ["morale", "moral", "mortal", "Immortal"],
  ["doorway", "doorstep"],
  ["evocative", "exacerbation", "evacuation", "excavation", 'exaggerate'],
  ["terrain", "terraced"],
  ["groves", "gloves"],
  ["geologic", "geometric", "geographic", "geothermal", "geology"],
  ["intend", "tend"],
  ["fudge", "fungus"],
  ["perspective", "perception", "prospect"],
  ["circumstance", "perimeter", "circumference"],
  ["proximity", "approximate"],
  ["breathe", "breath"],
  ["wiggle", "wobble"],
  ["leisure", "luxury"],
  ["juvenile", "rejuvenate"],
  ["ripple", "rip", "ripping"],
  ["stalk", "stake", "steak"],
  ["squelch", "squeal", "squeeze"],
  ["alien", "ally"],
  ["billow", "blow"],
  ["serenity", "serene"],
  ["hushed", "hustled"],
  ["deck", "desk", "dock"],
  ["cedar", "cider"],
  ["strap", "strip", "stride", "string", "striped"],
  ["tilt", "lilt"],
  ["pinnacle", "barnacle"],
  ["crest", "crescent"],
  ["chill", "chilly"],
  ["cranial", "crane"],
  ["scorch", "scour"],
  ["shuffle", "commute", "shuttle"],
  ["joint", "jolt"],
  ["bend", "blend"],
  ["founder", "funder", "fund", "found", "find"],
  ["reverse", "revert"],
  ["compete", "complete"],
  ["brake", "bake"],
  ["creative", "intellectual", "innovative", "ingenuity"],
  ["capital", "capita"],
  ["nocturnal", "necropolis"],
  ["pitch", "ditch"],
  ["lick", "flick"],
  ["mood", "moor"],
  ["glacier", "glacial"],
  ["yurt", "yacht"],
  ["gaze", "glaze"],
  ["interference", "intervening", "intervene"],
  ["raven", "ravine"],
  ["roar", "roam"],
  ["affront", "confront", "comfort"],
  ["sign", "sigh"],
  ["tense", "intense", "intensive", 'extensive', 'extent','expanse', 'expansion', 'expand', 'expansive'],
  ["visualize", "vision"],
  ["comprehensive", "comprehension"],
  ["prior", "priority"],
  ["isolated", "insulated"],
  ["bath", "bathe"],
  ["radical", "radiate"],
  ["plate", "platter", "tray"],
  ["picky", "prick"],
  ["complain", "comply", "comprise"],
  ["runway", "runaway"],
  ["tuxedo", "detox", "toxic", "dioxide"],
  ["toll", "tow", "toe"],
  ["tycoon", "magnate", "mogul", "magnet"],
  ["tick", "ticket"],
  ["squad", "squid"],
  ["synonym", "synonymous"],
  ["thrive", "strive"],
  ["ceremony", "cemetery"],
  ["grin", "grind"],
  ["illuminate", "illusion"],
  ["haunt", "haul", "hound"],
  ["diesel", "kerosene", "petrol", "patrol"],
  ["entwined", "intertwined"],
  ["spectrum", "spectre"],
  ["repute", "dispute", "deputy"],
  ["sturdy", "steady"],
  ["helm", "helmet", "hamlet"],
  ["lurk", "lurch"],
  ["crater", "crate", "cater"],
  ["iron", "steel", "copper", "aluminium"],
];
