const defaultWordGroups = [
  ["specific"],
  ["dinner","dinner"],
  ["checkout n1", "checkout n2", "check out"],
  ["atmosphere"],
  ["thrive", "strive", "strove", "endeavor"],
  ['ability', 'capacity'],
  ['inflammation', 'inflation'],
  ['flavour', 'favour', 'savour'],
  ['suit'],
  ['capacity', 'capability'],
  ['director', 'toddler', 'pragmatism'],
  ['content n', 'consume', 'content adj/v'],
  ['sew', 'sow'],
  ['democratic', 'democracy'],
  ['pillar', 'stick', 'post', 'stake'],
  ['console n', 'console v'],
  ['intimate', 'imitate'],
  ['footage', 'footstep', 'footprint'],
  ['strike', 'struck', 'stroke', 'stuck'],
  ["pitch", "ditch", "drench", "trench"],
  ['instead', 'instead of'],
  ['program', 'progress n', 'progress v', 'process n', "process v",'project'],
  ['irregularity'],
  ["complicated", "complex", "intricate", "sophisticated"],
  ["ceremony", "cemetery", 'celebration', 'ceremonial'],
  ["reconsider"],
  ["intrigue", 'intricate'],
  ["origin"],
  ["perspective", "perception", "prospect", "sense"],
  ["squad", "squid"],
  ["object n", "object v"],
  ["policies"],
  ["says"],
  ["conserve", "conservation", 'preserve', 'preservation', "recognize"],
  ["alert", "alarm"],
  ["woman", "women"],
  ["shepherd", 'herd', 'herb'],
  ["sheriff", "chef", 'chief'],
  ['repeat'],
  ['barren', 'barrier', 'barrel'],
  ['rotten', 'rodent'],
  ['shrub', 'shrug'],
  ['project'],
  ['basin'],
  ['particularly', 'obesity'],
  ['utter', 'usher'],
  ['miracle', 'miraculous', 'celebrity', 'excellent'],
  ['obscure', 'obstruct', 'obstacle'],
  ["stalk", "stake", "steak"],
  ['fabric', 'fabricate', 'prefabricate', 'fibre', 'facilitated', 'facility'],
  ['injuries'],
  ['occasion', 'occasionally'],
  ['innovative', 'original', 'origin'],
  ['petrol', 'patrol'],
  ['safari','savannah','patriarch', 'devastate'],
  ['nibble','nipple'],
  ['stir', 'stair', 'start'],
  ['perceive', 'perceived', 'perception'],
  ['rhythm', 'rhyme'],
  ['custom n', 'custom adj', 'custom n', 'custodian'],
  ['near', 'adjacent', 'adjoining', 'proximity'],
  ["security", 'proximity'],
  ["prey", "predator", "predate", "pray", "priest"],
  ['prefer', 'tend to'],
  ['cabin', 'cabinet'],
  ['sightseeing', 'sight', 'sighting'],
  ['encourage', 'matrix', 'secure', 'obsession', 'academy','implement', 'geography', 'geopolitical', 'month'],
  ["compete", "competitive","competition", "complete", "completion"],
  ["weekend", "weakened","inherit"],
  ["proximity", "approximate"],

  ['delight/n', 'delight/v', 'delightful'],
  ['import/v', 'import/n'],
  ['import/v', 'import/n'],
  ['tend', 'tender/adj', 'tender/n', 'trend'],
  ['passenger', 'passage'],
  ['ceiling','infestation', 'festival', 'academy', 'feast','feat', 'fest'],
  ['brace', 'embrace'],
  ['diligence', 'diligent', 'dignity', 'indignity','momentarily'],
  ['diligence', 'diligent', 'dignity', 'indignity'],
  ['official', 'officer'],
  ['organism', 'organization', 'mechanisms'],
  ['challenge', 'echo'],
  ['inherent', 'inherently', 'inherit'],
  ['infer', 'refer', 'inter', 'reference'],
  ['convict', 'victim'],
  ['mitigate', 'migrate'],
  ['yacht', 'yurt', 'jam', 'yam'],
  ['serenity', 'tranquilize', 'tranquility','solitude', 'silence', 'quiet', 'secluded', 'serene', 'tranquil'],
  ['civilian', 'citizen', 'civilisation'],
  ['serotonin', 'cortisol'],
  ['audiologist', 'physiological'],
  ['somewhat', 'somehow'],
  ['allergy', 'allergic'],
  ['liberate', 'deliberate'],
  ['hypothesize', 'hypothesis'],
  ['fur', 'flu'],
  ['foundation', 'fundamental'],
  ['intrigue', 'trudge', 'protrude'],
  ['intrigue', 'fascinate'],
  ['graffiti', 'giraffe'],
  ['maintenance'],
  ['instinct', 'natural', 'intuitive'],
  ['pesticide', 'suicide'],
  ['have got'],
  ['sub-soil', 'subway', 'submarine', 'subtitle'],
  ['rubble', 'rubber'],
  ['drain', 'drainage'],
  ['sample', 'sapling'],
  ['weapon', 'rations'],
  ['success', 'succeed', 'successful', 'successfully'],
  ['involve', 'evolve'],
  ['scenario', 'situation'],
  ['comment', 'remark'],
  ["tense", "intense", "intensive", 'extensive', 'extent','expanse', 'expansion', 'expand', 'expansive', "tension"],
  ['personnel', 'persona'],
  ['warfare', 'welfare'],
  ['strategy', 'strategic', 'tragedy', 'tragic'],
  ['meantime', 'meanwhile'],
  //I'll be ready soon. In the meantime, please have a seat.
  ['college', 'colleague'],
  ['numbering',],
  ['complement','supplement'],
  ['integrity'],
  ['genuine','genuinely'],
  ['fertilizer','fertility'],
  ['fatally','fatality', 'fatal'],
  ['handle', 'cope', 'tackle', 'solve', 'resolve'],
  ['growl', 'roar'],
  ['bound', 'bounce', 'hop', 'leap'],
  ['spill', 'spit', 'split', 'spilt'],
  ['border', 'broaden'],
  ['sedate', 'seduce'],
  ['depend on', 'rely on', 'contingent on', 'rest on', 'be subject to'],
  ['fatality', 'facilitate'],
  ['vibrant', 'vibrance', 'vibration', 'energy', 'energetic', 'vitality', 'vital', 'vitally', 'vigour', 'vigorous', 'vigorously'],
  ['slice', 'slash'],
  ['perfect - v', 'perfect - adj'],
  ['oceanic'],
  ['litigation', 'prosecution', 'sue'],
  ['injured'],
  ['council', 'consult'],
  ['mutual', 'mutualism'],
  ['laboratory'],
  ['burn', 'burned', 'burnt', 'burst'],
  ['religion', 'religiously', 'religious'],
  ['fungus', 'fungi'],
  ['tear - v', 'tear - n', 'torn', 'tore', 'torment', 'torture'],
  ['attribute to', 'be subject to'],
  ['analyses', 'analyse', 'analysis - 发音都不一样'],
  ['natural','nature'],
  ['economic','economy'],
  ['recipe', 'reception', 'receipt'],
  ['hinder', 'inhibit', 'deter'],
  ['coincide', 'coincidence'],
  ['opportunistic'],
  ['culture', 'cultivate', 'raise', 'rear', 'nurture'],
  ['literature', 'literacy', 'literal', 'literary','literate', 'illiterate'],
  ['facilitate', 'facility'],
  ['screen', 'filter'],
  ['rob', 'lob', 'lobby', 'loft', 'robe'],
  ['synthetic', 'synchronize', 'synchronic'],
  ['wire', 'weird', 'hard-wired'],
  ['attribute-verb'],
  ['unwind', 'rewind', 'wind'],
  ['coincide', 'coincidence'],
  ['den', 'dam'],
  ['penguin', 'pungent'],
  ['gravely', 'gravity'],
  ['scene', 'scenario', 'sequence', "episode"],
  ['loon', 'loom', 'lone'],
  ['rein', 'reign'],
  ['official', 'authority', 'administration'],//v,n  n
  ['icon', 'iconic', 'ironic'],
  ['fling', 'flying'],
  ['illicit', 'illegal'],
  ['bear', 'beard'],
  ['strategy', 'strategic'],
  ['prone', 'probe'],
  ['oversee', 'overlook'],
  ['saw', 'sew', 'sewer', 'sewer'],
  ["clan", "claw", 'clay'],
  ["hallow", "halloween", 'hollow'],
  ["contrary", "contrast"],
  ["reality", "realization", "real", "realistic", "realize", "realistically"],
  ["stalwart", "steward"],
  ["fairy", "fair"],
  ["iconic", "ironic"],
  ["gateway", "getaway"],
  ["venture", "adventure"],
  ["sore", "soar", "sour"],
  ["fierce", "fiery"],
  ["delve", "deplete"],
  ["paste", "pasta"],
  ["luxurious", "extravagance", "luxury"],
  ["immense", "imminent", "eminent"],
  ["heaven", "haven"],
  ["invoke", "revoke"],
  ["deference", "defer", "deter"],
  ["proactively", "provocatively"],
  ["bunk", "bunker"],
  ["crush", "crash", "rush"],
  ["hype", "hyper"],
  ["sympathy", "empathy"],
  ["reverent", "revere", "reverence", "reverend"],
  ["sublime", "subtle"],
  ["idyllic"],
  ["horde", "herd"],
  ["patron", "patrol", "patriot", "petrol", 'petroleum'],
  ["rural", "rustic",
    "pastoral",'rustle'],
  ["lush", "verdant"],
  ["meticulously", "malicious", "mischievous"],
  ["as opposed to", "instead of"],
  ["feat", "feast"],
  ["abundant", "abandon", "abandoned", 'abundance'],
  ["scare", "scarce", "scarcity"],
  ["shelves", "shelter"],
  ["congested", "contingent", "consign", 'consent'],
  ["tap", "tap into"],
  ["strike", "stroke", "struck", "stoke", "stork"],
  ["considerable", "considerate", 'sensitive'],
  ["initiative", "initiate", "initial", 'intuitive'],
  ["panoramic", "promenade", "lemonade"],
  ["inhabit", "habitat", "habitation", "inhabitant"],
  ["epidemic", "endemic"],
  ["eternal", "ethereal"],
  ["turf", "tuft"],
  ["aboard", "abroad", "board"],
  ["cottage", "cabbage", "carriage"],
  ["equine", "aquatic"],
  ["boast", "boost"],
  ["scrub", "succumb", "scurry"],
  ["spirit", "sprite"],
  ["indulging", "undulating"],
  ["flip", "flap"],
  ["captivate", "captive", "capture", "cavity"],
  ["lag", "lug", "tug"],
  ["loyal", "royal"],
  ["participate", "precipitate", "anticipate"],
  ["unite", "unit"],
  ["potato", "tomato"],
  ["couch", "coach"],
  ["avenue", "venue", "convention", "convene", 'convenience', "conventional"],
  ["vibrant", "vibrance", "vibe"],
  ["flank", "plank"],
  ["pedal", "paddle"],
  ["dust", "dusk", "dawn"],
  ["adorn", "adore"],
  ["bow", "bowl"],
  ["spire", "spine", "spindly", "spin"],
  ["stew", "strew", "straw"],
  ["captain", "subtitle", "caption"],
  ["sector", "section"],
  ["torch", "torture"],
  ["wonder", "wander"],
  ["concentric", "concentrate"],
  ["stump", "stamp"],
  ["incline", "recline", "decline", "descend", "descendant", "descent"],
  ["rumble", "scramble", "ramble"],
  ["hammock", "hummock"],
  ["forage", "forge", "foliage"],
  ["swamp", "swath"],
  ["clamp", "clump"],
  ["crucial", "cruel"],
  ["hospitable", "hostile", "hostel"],
  ['bear', 'born', 'bore'],
  ["tempt", "attempt", "contemporary", "contempt", "temp", "confront", "conform", "obey", "comply",'temper'],
  ["lavender", "vanilla"],
  ["assume", "unassuming"],
  ["reed", "reef"],
  ["specialist", "specialize", "special", "specialty"],
  ["handful", "handy"],
  ["incentive", "sensitive", "sensitize"],
  ["rough", "rugged", "jagged"],
  ["leash", "lease"],
  ["beckon", "reckon", "reckoning"],
  ["morale", "moral", "mortal", "Immortal"],
  ["doorway", "doorstep"],
  ["evocative", "exacerbation", "evacuation", "excavation", 'exaggerate'],
  ["terrain", "terraced"],
  ["groves", "gloves"],
  ["geologic", "geometric", "geographic", "geothermal", "geology", "geography"],
  ["intend", "tend"],
  ["fudge", "fungus"],
  ["circumstance", "perimeter", "circumference"],

  ["breathe", "breath"],
  ["wiggle", "wobble"],
  ["leisure", "luxury"],
  ["juvenile", "rejuvenate"],
  ["ripple", "rip", "ripping"],
  ["squelch", "squeal", "squeeze"],
  ["alien", "ally"],
  ["billow", "blow"],
  ["hushed", "hustled"],
  ["deck", "desk", "dock"],
  ["cedar", "cider"],
  ["strap", "strip", "stride", "string", "striped"],
  ["tilt", "lilt"],
  ["pinnacle", "barnacle"],
  ["crest", "crescent"],
  ["chill", "chilly"],
  ["cranial", "crane"],
  ["scorch", "scour"],
  ["shuffle", "commute", "shuttle"],
  ["joint", "jolt"],
  ["bend", "blend"],
  ["founder", "funder", "fund", "found", "find"],
  ["reverse", "revert"],
  ["compete", "complete"],
  ["brake", "bake"],
  ["creative", "intellectual", "innovative", "ingenuity"],
  ["capital", "capita"],
  ["nocturnal", "necropolis"],
  ["lick", "flick"],
  ["mood", "moor"],
  ["glacier", "glacial"],
  ["yurt", "yacht"],
  ["gaze", "glaze"],
  ["interference", "intervening", "intervene"],
  ["raven", "ravine"],
  ["roar", "roam"],
  ["affront", "confront", "comfort"],
  ["sign", "sigh"],

  ["visualize", "vision"],
  ["comprehensive", "comprehension"],
  ["prior", "priority"],
  ["isolated", "insulated"],
  ["bath", "bathe"],
  ["radical", "radiate", 'radiator'],
  ["plate", "platter", "tray"],
  ["picky", "prick"],
  ["complain", "comply", "comprise"],
  ["runway", "runaway"],
  ["tuxedo", "detox", "toxic", "dioxide"],
  ["toll", "tow", "toe"],
  ["tycoon", "magnate", "mogul", "magnet"],
  ["tick", "ticket"],
  ["synonym", "synonymous"],
  ["ceremony", "cemetery"],
  ["grin", "grind"],
  ["illuminate", "illusion"],
  ["haunt", "haul", "hound"],
  ["diesel", "kerosene", "petrol", "patrol"],
  ["entwined", "intertwined"],
  ["spectrum", "spectre"],
  ["repute", "dispute", "deputy"],
  ["sturdy", "steady"],
  ["helm", "helmet", "hamlet"],
  ["lurk", "lurch"],
  ["crater", "crate", "cater"],
  ["iron", "steel", "copper", "aluminium"],
];
