const defaultWordGroups = [
  ["contrary", "contrast"],
  ["reality", "realization", "real", "realistic", "realize", "realistically"],
  ["stalwart", "steward"],
  ["fairy", "fair"],
  ["iconic", "ironic"],
  ["gateway", "getaway"],
  ["venture", "adventure"],
  ["sore", "soar", "sour"],
  ["fierce", "fiery"],
  ["delve", "deplete"],
  ["paste", "pasta"],
  ["luxurious", "extravagance", "luxury"],
  ["immense", "imminent", "eminent"],
  ["heaven", "haven"],
  ["invoke", "revoke"],
  ["deference", "defer", "deter"],
  ["proactively", "provocatively"],
  ["bunk", "bunker"],
  ["ceremony", "cemetery"],
  ["crush", "crash", "rush"],
  ["hype", "hyper"],
  ["sympathy", "empathy"],
  ["reverent", "revere", "reverence", "reverend"],
  ["sublime", "subtle"],
  ["idyllic"],
  ["horde", "herd"],
  ["sheriff", "chef"],
  ["patron", "patrol", "patriot", "petrol"],
  ["rural", "rustic"],
  ["lush", "verdant"],
  ["meticulously", "malicious", "mischievous"],
  ["as opposed to", "instead of"],
  ["feat", "feast"],
  ["abundant", "abandon", "abandoned"],
  ["scare", "scarce", "scarcity"],
  ["shelves", "shelter"],
  ["congested", "contingent"],
  ["tap", "tap into"],
  ["strike", "stroke", "struck", "stoke", "stork"],
  ["considerable", "considerate"],
  ["initiative", "initiate", "initial"],
  ["panoramic", "promenade", "lemonade"],
  ["prey", "predator", "predate", "pray", "priest"],
  ["inhabit", "habitat", "habitation", "inhabitant"],
  ["epidemic", "endemic"],
  ["eternal", "ethereal"],
  ["turf", "tuft"],
  ["aboard", "abroad", "board"],
  ["cottage", "cabbage", "carriage"],
  ["equine", "aquatic"],
  ["boast", "boost"],
  ["scrub", "succumb", "scurry"],
  ["spirit", "sprite"],
  ["indulging", "undulating"],
  ["flip", "flap"],
  ["captivate", "captive", "capture"],
  ["lag", "lug", "tug"],
  ["loyal", "royal"],
  ["participate", "precipitate", "anticipate"],
  ["unite", "unit"],
  ["potato", "tomato"],
  ["couch", "coach"],
  ["avenue", "venue", "convention", "convene"],
  ["vibrant", "vibrance", "vibe"],
  ["flank", "plank"],
  ["pedal", "paddle"],
  ["dust", "dusk", "dawn"],
  ["adorn", "adore"],
  ["bow", "bowl"],
  ["spire", "spine", "spindly", "spin"],
  ["stew", "strew", "straw"],
  ["captain", "subtitle", "caption"],
  ["sector", "section"],
  ["torch", "torture"],
  ["wonder", "wander"],
  ["concentric", "concentrate"],
  ["stump", "stamp"],
  ["incline", "recline", "decline", "descend", "descendant"],
  ["rumble", "scramble", "ramble"],
  ["hammock", "hummock"],
  ["forage", "forge", "foliage"],
  ["swamp", "swath"],
  ["clamp", "clump"],
  ["crucial", "cruel"],
  ["hospitable", "hostile", "hostel"],
  ["tempt", "attempt", "contemporary", "contempt", "temp", "confront", "conform", "obey", "comply"],
  ["lavender", "vanilla"],
  ["assume", "unassuming"],
  ["reed", "reef"],
  ["specialist", "specialize", "special", "specialty"],
  ["handful", "handy"],
  ["incentive", "sensitive", "sensitize"],
  ["rough", "rugged", "jagged"],
  ["leash", "lease"],
  ["beckon", "reckon", "reckoning"],
  ["morale", "moral", "mortal", "Immortal"],
  ["doorway", "doorstep"],
  ["evocative", "exacerbation", "evacuation", "excavation"],
  ["terrain", "terraced"],
  ["groves", "gloves"],
  ["geologic", "geometric", "geographic", "geothermal", "geology"],
  ["intend", "tend"],
  ["fudge", "fungus"],
  ["perspective", "perception", "prospect"],
  ["circumstance", "perimeter", "circumference"],
  ["proximity", "approximate"],
  ["breathe", "breath"],
  ["wiggle", "wobble"],
  ["leisure", "luxury"],
  ["juvenile", "rejuvenate"],
  ["ripple", "rip", "ripping"],
  ["stalk", "stake", "steak"],
  ["squelch", "squeal", "squeeze"],
  ["alien", "ally"],
  ["billow", "blow"],
  ["serenity", "serene"],
  ["hushed", "hustled"],
  ["deck", "desk", "dock"],
  ["cedar", "cider"],
  ["strap", "strip", "stride", "string"],
  ["tilt", "lilt"],
  ["pinnacle", "barnacle"],
  ["crest", "crescent"],
  ["chill", "chilly"],
  ["cranial", "crane"],
  ["scorch", "scour"],
  ["shuffle", "commute", "shuttle"],
  ["joint", "jolt"],
  ["bend", "blend"],
  ["founder", "funder", "fund", "found", "find"],
  ["reverse", "revert"],
  ["compete", "complete"],
  ["brake", "bake"],
  ["creative", "intellectual", "innovative", "ingenuity"],
  ["capital", "capita"],
  ["nocturnal", "necropolis"],
  ["pitch", "ditch"],
  ["lick", "flick"],
  ["mood", "moor"],
  ["glacier", "glacial"],
  ["yurt", "yacht"],
  ["gaze", "glaze"],
  ["interference", "intervening", "intervene"],
  ["raven", "ravine"],
  ["roar", "roam"],
  ["affront", "confront", "comfort"],
  ["sign", "sigh"],
  ["tense", "intense"],
  ["visualize", "vision"],
  ["comprehensive", "comprehension"],
  ["prior", "priority"],
  ["isolated", "insulated"],
  ["bath", "bathe"],
  ["radical", "radiate"],
  ["plate", "platter", "tray"],
  ["picky", "prick"],
  ["complain", "comply", "comprise"],
  ["runway", "runaway"],
  ["tuxedo", "detox", "toxic", "dioxide"],
  ["toll", "tow", "toe"],
  ["tycoon", "magnate", "mogul", "magnet"],
  ["tick", "ticket"],
  ["squad", "squid"],
  ["synonym", "synonymous"],
  ["thrive", "strive"],
  ["ceremony", "cemetery"],
  ["grin", "grind"],
  ["illuminate", "illusion"],
  ["haunt", "haul", "hound"],
  ["diesel", "kerosene", "petrol", "patrol"],
  ["entwined", "intertwined"],
  ["spectrum", "spectre"],
  ["repute", "dispute", "deputy"],
  ["sturdy", "steady"],
  ["helm", "helmet", "hamlet"],
  ["lurk", "lurch"],
  ["crater", "crate", "cater"],
  ["iron", "steel", "copper", "aluminium"],
];
